Hotel.Atr.Admin/Controllers/SliderAreasController.cs
using System;
using System.Data.Entity;
using System.IO;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hotel.Atr.Web.Models.Model;
//using HotelAtr.DAL.Model;

namespace Hotel.Atr.Admin.Controllers
{
    public class SliderAreasController : Controller
    {
        private HotelAtrEntities db = new HotelAtrEntities();

        // GET: SliderAreas
        public async Task<ActionResult> Index()
        {
            return View(await db.SliderAreas.ToListAsync());
        }

        // GET: SliderAreas/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SliderArea sliderArea = await db.SliderAreas.FindAsync(id);
            if (sliderArea == null)
            {
                return HttpNotFound();
            }
            return View(sliderArea);
        }

        // GET: SliderAreas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SliderAreas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "SliderAreaId,Header,Description,Url,PathImg")] SliderArea sliderArea, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (!string.IsNullOrEmpty(file?.FileName))
                    {
                        if (string.IsNullOrEmpty(sliderArea.Url))
                            sliderArea.Url = file.FileName;

                        string path = Path.Combine(new DirectoryInfo(AppDomain.CurrentDomain.BaseDirectory).Parent?.FullName + @"\Hotel.Atr.Web\Content\img\slider", Path.GetFileName(file.FileName));
                        if (!System.IO.File.Exists(path))
                            file.SaveAs(path);

                        sliderArea.PathImg = Path.Combine(@"Content\img\slider", Path.GetFileName(file.FileName));

                        db.SliderAreas.Add(sliderArea);
                        await db.SaveChangesAsync();
                    }

                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }

                return RedirectToAction("Index");
            }

            return View();
            //sliderArea
        }

        // GET: SliderAreas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SliderArea sliderArea = await db.SliderAreas.FindAsync(id);
            if (sliderArea == null)
            {
                return HttpNotFound();
            }
            return View(sliderArea);
        }

        // POST: SliderAreas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "SliderAreaId,Header,Description,Url,PathImg")] SliderArea sliderArea)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sliderArea).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(sliderArea);
        }

        // GET: SliderAreas/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SliderArea sliderArea = await db.SliderAreas.FindAsync(id);
            if (sliderArea == null)
            {
                return HttpNotFound();
            }
            return View(sliderArea);
        }

        // POST: SliderAreas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            SliderArea sliderArea = await db.SliderAreas.FindAsync(id);
            if (sliderArea != null)
            {
                db.SliderAreas.Remove(sliderArea);

                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
            {
                return HttpNotFound();
            }



        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hotel.Atr.Admin/Views/SliderAreas/Create.cshtml
@model HotelAtr.DAL.Model.SliderArea

@{
    ViewBag.Title = "Создание";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Create", "SliderAreas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Слайда</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Header, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Header, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Header, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, "Вставьте ссылку из интернета , как альтернативу", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "Может быть пустым", new { @class = "text-success" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PathImg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("file", "", new { type = "file", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PathImg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Обратно к списку", "Index", null, htmlAttributes: new { @class = "btn btn-outline-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Hotel.Atr.Admin/Views/SliderAreas/Delete.cshtml
@model HotelAtr.DAL.Model.SliderArea

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SliderArea</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Header)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Header)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PathImg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PathImg)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="btn-group">
            <input type="submit" value="Delete" class="btn btn-outline-danger" />
            @Html.ActionLink("Back to List", "Index","SliderAreas",htmlAttributes:new{@class="btn btn-outline-primary"})
        </div>
    }
</div>

Hotel.Atr.Admin/Views/SliderAreas/Details.cshtml
@model HotelAtr.DAL.Model.SliderArea

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SliderArea</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Header)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Header)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PathImg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PathImg)
        </dd>

    </dl>
</div>
<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
    <div class="btn-group mr-2">
        @Html.ActionLink("Изменить", "Edit", new { id = Model.SliderAreaId }, new { @class = "btn btn-primary" })
    </div>
    <div class="btn-group">
        @Html.ActionLink("Обратно к списку", "Index", null, new { @class = "btn btn-outline-dark" })
    </div>
</div>

Hotel.Atr.Admin/Views/SliderAreas/Edit.cshtml
@model HotelAtr.DAL.Model.SliderArea

@{
    ViewBag.Title = "Edit";
}

<h2>Изменение</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Слайдера</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SliderAreaId)

        <div class="form-group">
            @Html.LabelFor(model => model.Header, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Header, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Header, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PathImg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PathImg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PathImg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <input type="submit" value="Сохранить изменения" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div class="container-fluid">
    @Html.ActionLink("Обратно к списку", "Index", null, htmlAttributes: new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Hotel.Atr.Admin/Views/SliderAreas/Index.cshtml
@using HotelAtr.DAL.Model
@model IEnumerable<HotelAtr.DAL.Model.SliderArea>

@{
    ViewBag.Title = "SliderArea" +
                    "Index";
}

<h3>Картинки для слайдеров</h3>

<p>
    @Html.ActionLink("Создать", "Create", "SliderAreas", new { @class = "btn btn-success" })
</p>
<table class="table table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Header)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Url)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PathImg)
        </th>
        <th></th>
    </tr>

    @foreach (SliderArea item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Header)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Url)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PathImg)
            </td>
            <td class="btn-group-sm">
                @Html.ActionLink("Edit", "Edit", new { id = item.SliderAreaId }, new { @class = "btn btn-primary" })
                @Html.ActionLink("Details", "Details", new { id = item.SliderAreaId }, new { @class = "btn btn-info" })
                @Html.ActionLink("Delete", "Delete", new { id = item.SliderAreaId }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>