Hotel.Atr.Admin/Controllers/RoomTypesController.cs
using System;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hotel.Atr.Web.Models.Model;
//using HotelAtr.DAL.Model;

namespace Hotel.Atr.Admin.Controllers
{
    public class RoomTypesController : BaseController
    {

        // GET: RoomTypes
        public async Task<ActionResult> Index()
        {
            return View(await db.RoomTypes.ToListAsync());
        }

        // GET: RoomTypes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomType roomType = await db.RoomTypes.FindAsync(id);
            if (roomType == null)
            {
                return HttpNotFound();
            }
            return View(roomType);
        }

        // GET: RoomTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "RoomTypeId,Name,RoomTypeDescription,Price,Imagepath")] RoomType roomType, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (!string.IsNullOrEmpty(file.FileName))
                    {
                        string path = Path.Combine(new DirectoryInfo(AppDomain.CurrentDomain.BaseDirectory).Parent?.FullName + @"\Hotel.Atr.Web\Content\img\room", Path.GetFileName(file.FileName));
                        if (!System.IO.File.Exists(path))
                            file.SaveAs(path);
                        roomType.Imagepath = Path.Combine(@"\Content\img\room", Path.GetFileName(file.FileName));

                        db.RoomTypes.Add(roomType);
                        await db.SaveChangesAsync();
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception e)
                {
                    Debug.WriteLine(e);
                }
                return View(roomType);
            }
            return View(roomType);
        }

        // GET: RoomTypes/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomType roomType = await db.RoomTypes.FindAsync(id);
            if (roomType == null)
            {
                return HttpNotFound();
            }
            return View(roomType);
        }

        // POST: RoomTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "RoomTypeId,Name,RoomTypeDescription,Price,Imagepath")] RoomType roomType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(roomType).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(roomType);
        }

        // GET: RoomTypes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomType roomType = await db.RoomTypes.FindAsync(id);
            if (roomType == null)
            {
                return HttpNotFound();
            }
            return View(roomType);
        }

        // POST: RoomTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            RoomType roomType = await db.RoomTypes.FindAsync(id);
            db.RoomTypes.Remove(roomType);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hotel.Atr.Admin/Views/RoomTypes/Create.cshtml
@model HotelAtr.DAL.Model.RoomType

@{
    ViewBag.Title = "Создание";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Create", "RoomTypes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Типа комнаты</h4>
        <hr />
        <div class="form-group">
            @Html.ValidationSummary(false, "Заполните все поля", new { @class = "text-danger col-md-4" })
            @Html.LabelFor(model => model.Name, "Наименование типа комнаты", htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Name, "Поле обязательно для заполнения", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomTypeDescription, "Описание", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoomTypeDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoomTypeDescription, "Поле обязательно для заполнения", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, "Цена", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "Поле обязательно для заполнения", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagepath, "Выберите картинку для отображения", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("file", "Ничего", htmlAttributes: new { @class = "form-control", type = "file" })
                @Html.ValidationMessageFor(model => model.Imagepath, "Поле обязательно для заполнения", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div class="container-fluid">
    @Html.ActionLink("Вернуться к списку", "Index", null, htmlAttributes: new { @class = "btn btn-sm btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Hotel.Atr.Admin/Views/RoomTypes/Delete.cshtml
@model HotelAtr.DAL.Model.RoomType

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RoomType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoomTypeDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomTypeDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagepath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagepath)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Hotel.Atr.Admin/Views/RoomTypes/Details.cshtml
@model HotelAtr.DAL.Model.RoomType

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>RoomType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoomTypeDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomTypeDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagepath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagepath)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RoomTypeId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Hotel.Atr.Admin/Views/RoomTypes/Edit.cshtml
@model HotelAtr.DAL.Model.RoomType

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RoomType</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RoomTypeId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomTypeDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoomTypeDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoomTypeDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagepath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imagepath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Imagepath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Hotel.Atr.Admin/Views/RoomTypes/Index.cshtml
@using HotelAtr.DAL.Model
@model IEnumerable<RoomType>

@{
    ViewBag.Title = "Список типов комнаты";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Создать новый тип комнаты", "Create", "RoomTypes", htmlAttributes: new { @class = "btn btn-primary" })
</p>
<table class="table table-hover table-bordered">
    <tr>
        <th>
            Наименование типа
        </th>
        <th>
            Цена
        </th>
        <th></th>
    </tr>

    @foreach (RoomType item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                <div class="btn-group mr-2">
                    @Html.ActionLink("Изменить", "Edit", new { id = item.RoomTypeId }, new { @class = "btn btn-primary" })
                </div>
                <div class="btn-group mr-2">
                    @Html.ActionLink("Посмотреть детали", "Details", new { id = item.RoomTypeId }, new { @class = "btn btn-info" })
                </div>
                <div class="btn-group">
                    @Html.ActionLink("Удалить", "Delete", new { id = item.RoomTypeId }, new { @class = "btn btn-danger" })
                </div>
            </td>
        </tr>
    }
</table>